//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.349.0.
namespace EawXBuild.Configuration.v1
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CopyTaskType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CopyTaskType
    {
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(/[a-z0-9]([a-z0-9-]*[a-z0-9])?)*(/[a-z0-9]([a-z0-9-.]*[a-z0-9])?)?$.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("^[a-z0-9]([a-z0-9-]*[a-z0-9])?(/[a-z0-9]([a-z0-9-]*[a-z0-9])?)*(/[a-z0-9]([a-z0-9" +
            "-.]*[a-z0-9])?)?$")]
        [System.Xml.Serialization.XmlElementAttribute("SourcePath")]
        public string SourcePath { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ^[a-z0-9]([a-z0-9-]*[a-z0-9])?(/[a-z0-9]([a-z0-9-]*[a-z0-9])?)*(/[a-z0-9]([a-z0-9-.]*[a-z0-9])?)?$.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("^[a-z0-9]([a-z0-9-]*[a-z0-9])?(/[a-z0-9]([a-z0-9-]*[a-z0-9])?)*(/[a-z0-9]([a-z0-9" +
            "-.]*[a-z0-9])?)?$")]
        [System.Xml.Serialization.XmlElementAttribute("DestPath")]
        public string DestPath { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Recursive")]
        public bool Recursive { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ((\*[a-zA-Z0-9_-]*)(.)([a-zA-Z]+)|\*).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("((\\*[a-zA-Z0-9_-]*)(.)([a-zA-Z]+)|\\*)")]
        [System.Xml.Serialization.XmlElementAttribute("FilePattern")]
        public string FilePattern { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaskDefinitionType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaskDefinitionType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CopyTask")]
        public CopyTaskType CopyTask { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaskReferenceType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaskReferenceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("TaskName")]
        public string TaskName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GlobalTaskDefinitionsType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GlobalTaskDefinitionsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TaskDefinitionType> _taskDefinition;
        
        [System.Xml.Serialization.XmlElementAttribute("TaskDefinition")]
        public System.Collections.ObjectModel.Collection<TaskDefinitionType> TaskDefinition
        {
            get
            {
                return this._taskDefinition;
            }
            private set
            {
                this._taskDefinition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die TaskDefinition-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the TaskDefinition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaskDefinitionSpecified
        {
            get
            {
                return (this.TaskDefinition.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="GlobalTaskDefinitionsType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GlobalTaskDefinitionsType" /> class.</para>
        /// </summary>
        public GlobalTaskDefinitionsType()
        {
            this._taskDefinition = new System.Collections.ObjectModel.Collection<TaskDefinitionType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaskType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaskType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CopyTask")]
        public CopyTaskType CopyTask { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("TaskReference")]
        public TaskReferenceType TaskReference { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TasksType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TasksType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public TaskType Task { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JobType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TasksType> _tasks;
        
        [System.Xml.Serialization.XmlElementAttribute("Tasks")]
        public System.Collections.ObjectModel.Collection<TasksType> Tasks
        {
            get
            {
                return this._tasks;
            }
            private set
            {
                this._tasks = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JobType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JobType" /> class.</para>
        /// </summary>
        public JobType()
        {
            this._tasks = new System.Collections.ObjectModel.Collection<TasksType>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JobsType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JobType> _job;
        
        [System.Xml.Serialization.XmlElementAttribute("Job")]
        public System.Collections.ObjectModel.Collection<JobType> Job
        {
            get
            {
                return this._job;
            }
            private set
            {
                this._job = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Job-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Job collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobSpecified
        {
            get
            {
                return (this.Job.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="JobsType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="JobsType" /> class.</para>
        /// </summary>
        public JobsType()
        {
            this._job = new System.Collections.ObjectModel.Collection<JobType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProjectType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<JobType> _jobs;
        
        [System.Xml.Serialization.XmlArrayAttribute("Jobs")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Job")]
        public System.Collections.ObjectModel.Collection<JobType> Jobs
        {
            get
            {
                return this._jobs;
            }
            private set
            {
                this._jobs = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Jobs-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Jobs collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JobsSpecified
        {
            get
            {
                return (this.Jobs.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ProjectType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProjectType" /> class.</para>
        /// </summary>
        public ProjectType()
        {
            this._jobs = new System.Collections.ObjectModel.Collection<JobType>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ProjectsType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectType> _project;
        
        [System.Xml.Serialization.XmlElementAttribute("Project")]
        public System.Collections.ObjectModel.Collection<ProjectType> Project
        {
            get
            {
                return this._project;
            }
            private set
            {
                this._project = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Project-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Project collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProjectSpecified
        {
            get
            {
                return (this.Project.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ProjectsType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ProjectsType" /> class.</para>
        /// </summary>
        public ProjectsType()
        {
            this._project = new System.Collections.ObjectModel.Collection<ProjectType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BuildConfigurationType", Namespace="eaw-ci")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("BuildConfiguration", Namespace="eaw-ci")]
    public partial class BuildConfigurationType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TaskDefinitionType> _globalTaskDefinitions;
        
        [System.Xml.Serialization.XmlArrayAttribute("GlobalTaskDefinitions")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaskDefinition")]
        public System.Collections.ObjectModel.Collection<TaskDefinitionType> GlobalTaskDefinitions
        {
            get
            {
                return this._globalTaskDefinitions;
            }
            private set
            {
                this._globalTaskDefinitions = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die GlobalTaskDefinitions-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the GlobalTaskDefinitions collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GlobalTaskDefinitionsSpecified
        {
            get
            {
                return (this.GlobalTaskDefinitions.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="BuildConfigurationType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BuildConfigurationType" /> class.</para>
        /// </summary>
        public BuildConfigurationType()
        {
            this._globalTaskDefinitions = new System.Collections.ObjectModel.Collection<TaskDefinitionType>();
            this._projects = new System.Collections.ObjectModel.Collection<ProjectType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProjectType> _projects;
        
        [System.Xml.Serialization.XmlArrayAttribute("Projects")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Project")]
        public System.Collections.ObjectModel.Collection<ProjectType> Projects
        {
            get
            {
                return this._projects;
            }
            private set
            {
                this._projects = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-" +
            "Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[" +
            "0-9a-zA-Z-]+)*))?$")]
        [System.Xml.Serialization.XmlAttributeAttribute("Version")]
        public string Version { get; set; }
    }
}
